name: churn_modeling  # Replace with your environment name if needed
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - jupyter
  - streamlit  # Installing Streamlit through conda for stability
  - pip  # Ensures pip packages are installed within the conda environment
  - pip:
      - tensorflow==2.17.0
      - tensorboard
      - scikeras
      - scikit-optimize

# conda env update --file environment.yml --name churn_modeling 